### ISSUE TITLE
next@8.1.0 breaks next-plugin-transpile-modules@2.0.0

### ISSUE THREAD

**Issue by AlenPelin** [josephluck/next-typescript-monorepo#3]
After updating `next-plugin-transpile-modules@2.0.0` and `next@8.1.0` this example stops working.

Note [next@8.1.0 requires React 16.8+](https://github.com/zeit/next.js/issues/7073).

**Steps to reproduce:**
```
yarn
cd blog
yarn add next-plugin-transpile-modules@2.0.0
yarn add next@8.1.0
yarn add react@16.8
yarn dev
```

**Actual Result:**
```
[ info ]  waiting on http://localhost:3000 ...
TypeError: Cannot read property 'map' of undefined
    at Object.webpack (C:\Users\Alen\Desktop\next-typescript-monorepo\node_modules\next-plugin-transpile-modules\index.js:32:43)
    at Object.webpack (C:\Users\Alen\Desktop\next-typescript-monorepo\node_modules\@zeit\next-typescript\index.js:57:27)
    at Object.webpack (C:\Users\Alen\Desktop\next-typescript-monorepo\node_modules\next-plugin-custom-babel-config\index.js:16:27)
    at getBaseWebpackConfig (C:\Users\Alen\Desktop\next-typescript-monorepo\node_modules\next\dist\build\webpack-config.js:23:1263)
    at async Promise.all (index 0)
    at async HotReloader.start (C:\Users\Alen\Desktop\next-typescript-monorepo\node_modules\next\dist\server\hot-reloader.js:15:1702)
    at async DevServer.prepare (C:\Users\Alen\Desktop\next-typescript-monorepo\node_modules\next\dist\server\next-dev-server.js:5:551)
    at async C:\Users\Alen\Desktop\next-typescript-monorepo\node_modules\next\dist\cli\next-dev.js:22:672
error Command failed with exit code 1.
```

**Comment by AlenPelin** [comment]
`next@8.0.0` works fine, so it is relatively recent change.

**Comment by AlenPelin** [comment]
It works fine with `next@8.0.5-canary.27` and breaks with `next@8.0.5-canary.28`

**Comment by AlenPelin** [comment]
The root case seems to be this change:
https://github.com/zeit/next.js/commit/a5ad06f99b597615e91e3fc8e96dd11e6f5f6f5f

**Comment by AlenPelin** [comment]
https://github.com/wellcometrust/next-plugin-transpile-modules/issues/11

**Comment by josephluck** [comment]
Great debugging and thanks for taking a look at this 👍
